name: Splitter
language: python
variables:
  - name: input
    inputType: InputTopic
    description: Name of the input topic to listen to.
    required: false
  - name: gps
    inputType: OutputTopic
    description: Name of the output topic to write to.
    defaultValue: gps
    required: true
  - name: gforce_topic
    inputType: OutputTopic
    description: ''
    defaultValue: gforce
    required: true
dockerfile: build/dockerfile
runEntryPoint: main.py
defaultFile: main.py
