name: Streamlit Dashboard
language: python
variables:
  - name: INFLUXDB_TOKEN
    inputType: Secret
    description: ''
    defaultValue: influx_token
    required: false
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
libraryItemId: streamlit
