name: FleetConsole Websockets
language: Python
variables:
  - name: input
    inputType: InputTopic
    description: Output topic
    defaultValue: sensor-data
    required: true
  - name: events_topic
    inputType: InputTopic
    description: Output topic
    defaultValue: events
    required: true
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
