name: JSON replay
language: python
variables:
  - name: output
    inputType: OutputTopic
    description: Name of the output topic to write into
    defaultValue: f1-data
    required: true
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
