# Use the official Prometheus Docker image
FROM prom/prometheus:latest

# Copy Prometheus configuration file into the container
COPY prometheus.yml /etc/prometheus/prometheus.yml

# Set Prometheus as the entrypoint
ENTRYPOINT [ "/bin/prometheus" ]

# Set command to specify the config file
CMD [ "--config.file=/etc/prometheus/prometheus.yml" ]