name: snowflake-sink
language: python
variables:
  - name: string
    inputType: FreeText
    multiline: true
    description: string
    defaultValue: string
    required: true
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
libraryItemId: starter-destination
