name: snowflake-sink
language: python
variables:
  - name: CONSUMER_GROUP
    inputType: FreeText
    defaultValue: Necessary for Kafka consumer group.
    required: true
  - name: TABLE_NAME
    inputType: FreeText
    defaultValue: The name of the table in Snowflake.
    required: true
  - name: DATABASE
    inputType: FreeText
    defaultValue: Snowflake database name.
    required: true
  - name: SCHEMA
    inputType: FreeText
    defaultValue: Snowflake schema name.
    required: true
  - name: WAREHOUSE
    inputType: FreeText
    defaultValue: Snowflake warehouse name.
    required: true
  - name: USER
    inputType: FreeText
    defaultValue: Snowflake user name.
    required: true
  - name: PASSWORD
    inputType: FreeText
    defaultValue: Snowflake password.
    required: true
  - name: ACCOUNT
    inputType: FreeText
    defaultValue: Snowflake account identifier (e.g., 'xy12345.east-us-2').
    required: true
  - name: input
    inputType: FreeText
    defaultValue: Identifier for the input topic.
    required: true
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
libraryItemId: big-query-sink
