name: snowflake-sink
language: python
variables:
  - name: CONSUMER_GROUP
    inputType: FreeText
    defaultValue: snowflakesink
    required: true
  - name: DATABASE
    inputType: FreeText
    defaultValue: QUIX
    required: true
  - name: SCHEMA
    inputType: FreeText
    defaultValue: DEFAULT
    required: true
  - name: SNOWFLAKE_ACCOUNT
    inputType: FreeText
    defaultValue: <correct_snowflake_account>
    required: true
  - name: SNOWFLAKE_PASSWORD
    inputType: FreeText
    defaultValue: <correct_password>
    required: true
  - name: SNOWFLAKE_USER
    inputType: FreeText
    defaultValue: <correct_username>
    required: true
  - name: WAREHOUSE
    inputType: FreeText
    defaultValue: COMPUTE_WH
    required: true
  - name: input
    inputType: FreeText
    defaultValue: sensor-data
    required: true
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
libraryItemId: big-query-sink
