name: snowflake-sink
language: python
variables:
  - name: TABLE_NAME
    inputType: FreeText
    defaultValue: Obtain from your Snowflake instance
    required: true
  - name: WAREHOUSE
    inputType: FreeText
    defaultValue: Obtain from your Snowflake instance
    required: true
  - name: DATABASE
    inputType: FreeText
    defaultValue: Obtain from your Snowflake instance
    required: true
  - name: SCHEMA
    inputType: FreeText
    defaultValue: Obtain from your Snowflake instance
    required: true
  - name: ACCOUNT
    inputType: FreeText
    defaultValue: Obtain from your Snowflake instance
    required: true
  - name: USER
    inputType: FreeText
    defaultValue: Obtain from your Snowflake instance
    required: true
  - name: PASSWORD
    inputType: FreeText
    defaultValue: Obtain from your Snowflake instance
    required: true
  - name: CONSUMER_GROUP
    inputType: FreeText
    defaultValue: Obtain from your Kafka instance
    required: true
  - name: input
    inputType: FreeText
    defaultValue: Obtain from your Kafka instance
    required: true
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
libraryItemId: big-query-sink
