name: snowflake-sink
language: python
variables:
  - name: CONSUMER_GROUP
    inputType: FreeText
    defaultValue: snowflakesink
    required: true
  - name: DATABASE
    inputType: FreeText
    defaultValue: QUIX
    required: true
  - name: SCHEMA
    inputType: FreeText
    defaultValue: DEFAULT
    required: true
  - name: ACCOUNT
    inputType: FreeText
    defaultValue: snowflakeaccountidentifier
    required: true
  - name: PASSWORD
    inputType: FreeText
    defaultValue: BLdJC4n.LQpQ7svFkujD
    required: true
  - name: USER
    inputType: FreeText
    defaultValue: tomasneubauer
    required: true
  - name: WAREHOUSE
    inputType: FreeText
    defaultValue: COMPUTE_WH
    required: true
  - name: input
    inputType: FreeText
    defaultValue: sensor-data
    required: true
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
libraryItemId: big-query-sink
