name: snowflake-sink
language: python
variables:
  - name: SNOWFLAKE_USER
    inputType: FreeText
    defaultValue: Please refer to your Snowflake Account page for username
    required: true
  - name: SNOWFLAKE_PASSWORD
    inputType: FreeText
    defaultValue: Please refer to your Snowflake Account page for password
    required: true
  - name: SNOWFLAKE_WAREHOUSE
    inputType: FreeText
    defaultValue: Please refer to your Snowflake Account page for warehouse ID
    required: true
  - name: SNOWFLAKE_DATABASE
    inputType: FreeText
    defaultValue: Please refer to your Snowflake Account page for database name
    required: true
  - name: SNOWFLAKE_SCHEMA
    inputType: FreeText
    defaultValue: Please refer to your Snowflake Account page for schema name
    required: true
  - name: CONSUMER_GROUP
    inputType: FreeText
    defaultValue: Please refer to the consumer group of your Kafka streaming source
    required: true
  - name: input
    inputType: FreeText
    defaultValue: Please refer to the topic of your Kafka streaming source
    required: true
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
libraryItemId: big-query-sink
