name: snowflake-sink
language: python
variables:
  - name: SNOWFLAKE_ACCOUNT
    inputType: FreeText
    defaultValue: Your Snowflake account here
    required: true
  - name: SNOWFLAKE_USER
    inputType: FreeText
    defaultValue: Your Snowflake username here
    required: true
  - name: SNOWFLAKE_PASSWORD
    inputType: FreeText
    defaultValue: Your Snowflake password here
    required: true
  - name: DATABASE
    inputType: FreeText
    defaultValue: Your Snowflake database name here
    required: true
  - name: SCHEMA
    inputType: FreeText
    defaultValue: Your Snowflake schema here
    required: true
  - name: WAREHOUSE
    inputType: FreeText
    defaultValue: Your Snowflake warehouse here
    required: true
  - name: CONSUMER_GROUP
    inputType: FreeText
    defaultValue: Your QuixStreams consumer group here
    required: true
  - name: input
    inputType: FreeText
    defaultValue: Your QuixStreams input topic here
    required: true
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
libraryItemId: big-query-sink
