name: snowflake-sink
language: python
variables:
  - name: TABLE_NAME
    inputType: FreeText
    defaultValue: Obtain from Snowflake
    required: true
  - name: WAREHOUSE
    inputType: FreeText
    defaultValue: Obtain from Snowflake
    required: true
  - name: DATABASE
    inputType: FreeText
    defaultValue: Obtain from Snowflake
    required: true
  - name: SCHEMA
    inputType: FreeText
    defaultValue: Obtain from Snowflake
    required: true
  - name: ACCOUNT
    inputType: FreeText
    defaultValue: Obtain from Snowflake
    required: true
  - name: USER
    inputType: FreeText
    defaultValue: Obtain from Snowflake
    required: true
  - name: PASSWORD
    inputType: FreeText
    defaultValue: Obtain from Snowflake
    required: true
  - name: CONSUMER_GROUP
    inputType: FreeText
    defaultValue: Obtain from Kafka
    required: true
  - name: input
    inputType: FreeText
    defaultValue: Obtain from Kafka
    required: true
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
libraryItemId: starter-destination
