name: snowflake-sink
language: python
variables:
  - name: SNOWFLAKE_ACCOUNT
    inputType: FreeText
    defaultValue: Retrieve this from your Snowflake account identifier.
    required: true
  - name: SNOWFLAKE_USER
    inputType: FreeText
    defaultValue: Your Snowflake username.
    required: true
  - name: SNOWFLAKE_PASSWORD
    inputType: FreeText
    defaultValue: Your Snowflake password.
    required: true
  - name: DATABASE
    inputType: FreeText
    defaultValue: The Snowflake database to use.
    required: true
  - name: SCHEMA
    inputType: FreeText
    defaultValue: The Snowflake schema to use.
    required: true
  - name: WAREHOUSE
    inputType: FreeText
    defaultValue: The Snowflake warehouse to use.
    required: true
  - name: TABLE_NAME
    inputType: FreeText
    defaultValue: The name of the destination table in Snowflake.
    required: true
  - name: CONSUMER_GROUP
    inputType: FreeText
    defaultValue: The consumer group for your Quix streams application.
    required: true
  - name: input
    inputType: FreeText
    defaultValue: The input topic name for your Quix streams application.
    required: true
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
libraryItemId: big-query-sink
