name: snowflake-sink
language: python
variables:
  - name: USER
    inputType: FreeText
    defaultValue: Snowflake user
    required: true
  - name: PASSWORD
    inputType: FreeText
    defaultValue: Snowflake password
    required: true
  - name: ACCOUNT
    inputType: FreeText
    defaultValue: Snowflake account
    required: true
  - name: WAREHOUSE
    inputType: FreeText
    defaultValue: Snowflake warehouse
    required: true
  - name: DATABASE
    inputType: FreeText
    defaultValue: Snowflake database
    required: true
  - name: SCHEMA
    inputType: FreeText
    defaultValue: Snowflake schema
    required: true
  - name: CONSUMER_GROUP
    inputType: FreeText
    defaultValue: Kafka consumer group
    required: true
  - name: input
    inputType: FreeText
    defaultValue: Kafka input topic
    required: true
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
libraryItemId: big-query-sink
