name: snowflake-sink
language: python
variables:
  - name: CONSUMER_GROUP
    inputType: FreeText
    defaultValue: Obtain from Kafka details
    required: true
  - name: SNOWFLAKE_ACCOUNT
    inputType: FreeText
    defaultValue: Obtain from Snowflake account details
    required: true
  - name: SNOWFLAKE_DATABASE
    inputType: FreeText
    defaultValue: Obtain from Snowflake account details
    required: true
  - name: SNOWFLAKE_PASSWORD
    inputType: FreeText
    defaultValue: Obtain from Snowflake account details
    required: true
  - name: SNOWFLAKE_ROLE
    inputType: FreeText
    defaultValue: Obtain from Snowflake account details
    required: true
  - name: SNOWFLAKE_SCHEMA
    inputType: FreeText
    defaultValue: Obtain from Snowflake account details
    required: true
  - name: SNOWFLAKE_TABLE
    inputType: FreeText
    defaultValue: Obtain from Snowflake account details
    required: true
  - name: SNOWFLAKE_USER
    inputType: FreeText
    defaultValue: Obtain from Snowflake account details
    required: true
  - name: SNOWFLAKE_WAREHOUSE
    inputType: FreeText
    defaultValue: Obtain from Snowflake account details
    required: true
  - name: input
    inputType: FreeText
    defaultValue: Obtain from Kafka details
    required: true
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
libraryItemId: big-query-sink
