name: snowflake-sink
language: python
variables:
  - name: TABLE_NAME
    inputType: FreeText
    description: ''
    defaultValue: SENSORDATA
    required: true
  - name: DATABASE
    inputType: FreeText
    defaultValue: Snowflake database name
    required: true
  - name: SCHEMA
    inputType: FreeText
    defaultValue: Snowflake schema name
    required: true
  - name: USER
    inputType: FreeText
    defaultValue: Snowflake user account name
    required: true
  - name: PASSWORD
    inputType: FreeText
    defaultValue: Snowflake account password
    required: true
  - name: ACCOUNT
    inputType: FreeText
    defaultValue: Snowflake account identifier without special characters
    required: true
  - name: WAREHOUSE
    inputType: FreeText
    defaultValue: Snowflake virtual warehouse
    required: true
  - name: CONSUMER_GROUP
    inputType: FreeText
    defaultValue: Kafka consumer group used by QuixStreams
    required: true
  - name: input
    inputType: FreeText
    defaultValue: Input Kafka topic to consume from
    required: true
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
libraryItemId: big-query-sink
