name: snowflake-sink
language: python
variables:
  - name: ACCOUNT
    inputType: FreeText
    defaultValue: Your Snowflake account name
    required: true
  - name: CONSUMER_GROUP
    inputType: FreeText
    defaultValue: Your Kafka consumer group
    required: true
  - name: DB
    inputType: FreeText
    defaultValue: Your Snowflake database
    required: true
  - name: PASSWORD
    inputType: FreeText
    defaultValue: Your Snowflake password
    required: true
  - name: ROLE
    inputType: FreeText
    defaultValue: Your Snowflake role
    required: true
  - name: SCHEMA
    inputType: FreeText
    defaultValue: Your Snowflake schema
    required: true
  - name: TABLE
    inputType: FreeText
    defaultValue: Your Snowflake table
    required: true
  - name: USER
    inputType: FreeText
    defaultValue: Your Snowflake username
    required: true
  - name: WAREHOUSE
    inputType: FreeText
    defaultValue: Your Snowflake warehouse
    required: true
  - name: input
    inputType: FreeText
    defaultValue: Your Kafka input topic
    required: true
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
libraryItemId: starter-destination
