name: snowflake-sink
language: python
variables:
  - name: SNOWFLAKE_TABLE
    inputType: FreeText
    defaultValue: <your_snowflake_table>
    required: true
  - name: SNOWFLAKE_WAREHOUSE
    inputType: FreeText
    defaultValue: <your_snowflake_warehouse>
    required: true
  - name: SNOWFLAKE_DATABASE
    inputType: FreeText
    defaultValue: <your_snowflake_database>
    required: true
  - name: SNOWFLAKE_SCHEMA
    inputType: FreeText
    defaultValue: <your_snowflake_schema>
    required: true
  - name: SNOWFLAKE_ROLE
    inputType: FreeText
    defaultValue: <your_snowflake_role>
    required: true
  - name: SNOWFLAKE_USER
    inputType: FreeText
    defaultValue: <your_snowflake_user>
    required: true
  - name: SNOWFLAKE_PASSWORD
    inputType: FreeText
    defaultValue: <your_snowflake_password>
    required: true
  - name: CONSUMER_GROUP
    inputType: FreeText
    defaultValue: <your_consumer_group>
    required: true
  - name: input
    inputType: FreeText
    defaultValue: <your_input_topic>
    required: true
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
libraryItemId: big-query-sink
