# Use the official Grafana image from the Docker Hub
FROM grafana/grafana:latest

# Set the working directory inside the container
WORKDIR /app




RUN mkdir -p /app/state

# Create necessary directories with appropriate permissions
RUN mkdir -p /app/state/data /app/state/logs /app/state/plugins /app/state/provisioning /app/state/dashboards

# Copy custom configuration file
COPY custom.ini /etc/grafana/grafana.ini

COPY dashboards/14845_rev5.json /app/state/dashboards

# Set environment variables to point to /state/ folder
ENV GF_PATHS_DATA=/app/state/data \
    GF_PATHS_LOGS=/app/state/logs \
    GF_PATHS_PLUGINS=/app/state/plugins \
    GF_PATHS_PROVISIONING=/app/state/provisioning \
    GF_DASHBOARDS_PATH=/app/state/dashboards

# Set environment variables for the admin user and password
ENV GF_SECURITY_ADMIN_USER=admin_user \
    GF_SECURITY_ADMIN_PASSWORD=admin_password

# Expose Grafana port (default is 3000)
EXPOSE 3000

# Optionally, override Grafana's default port (uncomment to enable)
# ENV GF_SERVER_HTTP_PORT=80

# Command to start Grafana
CMD ["grafana-server", "--homepath=/usr/share/grafana"]