# Use the official Grafana image from the Docker Hub
FROM grafana/grafana:latest

# Set the working directory inside the container
WORKDIR /app

# Copy custom configuration file
COPY custom.ini /etc/grafana/grafana.ini

RUN mkdir -p /app/state/

#Set environment variables to point to /state/ folder
ENV GF_PATHS_DATA=/app/state/data \
    GF_PATHS_LOGS=/app/state/logs \
    GF_PATHS_PLUGINS=/app/state/plugins \
    GF_PATHS_PROVISIONING=/app/state/provisioning

# Expose port 80
EXPOSE 80

# Override Grafana's default port (3000) with port 80
#ENV GF_SERVER_HTTP_PORT=80

# Command to start Grafana
CMD ["grafana-server", "--homepath=/usr/share/grafana", "--config=/etc/grafana/grafana.ini"]