name: ShakeDetection
language: python
variables:
  - name: input
    inputType: InputTopic
    description: Name of the input topic to listen to.
    defaultValue: phone-data
    required: true
  - name: output
    inputType: OutputTopic
    description: Name of the output topic to write to.
    defaultValue: events
    required: true
  - name: model
    inputType: FreeText
    description: ''
    defaultValue: XGB_model_1.3.pkl
    required: true
dockerfile: build/dockerfile
runEntryPoint: main.py
defaultFile: main.py
