name: Telegraf source
language: docker
variables:
  - name: output
    inputType: OutputTopic
    description: ''
    defaultValue: telegraf
    required: false
dockerfile: dockerfile
defaultFile: dockerfile
libraryItemId: telegraf-source
