FROM mongo:latest

# Create the /state directory
RUN mkdir -p /state && chown -R mongodb:mongodb /state

# Set MongoDB to use /state as the data directory
CMD ["mongod", "--dbpath", "/state", "--bind_ip_all"]

# Expose MongoDB default port
EXPOSE 27017
