name: f1-demo-transformation
language: Python
variables:
  - name: input
    inputType: InputTopic
    description: Name of the input topic to listen to.
    defaultValue: raw
    required: false
  - name: output
    inputType: OutputTopic
    description: Name of the output topic to write to.
    defaultValue: f1-demo-normalised
    required: false
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
