name: snowflake
language: python
variables:
  - name: input
    inputType: InputTopic
    description: Name of the input topic to listen to.
    defaultValue: sensor-data
    required: false
  - name: ACCOUNT
    inputType: FreeText
    description: ''
    defaultValue: XY66326
    required: false
  - name: USER
    inputType: FreeText
    description: ''
    defaultValue: tomasneubauer
    required: false
  - name: PASSWORD
    inputType: Secret
    description: ''
    defaultValue: SNOWFLAKE_PASSWORD
    required: false
  - name: WAREHOUSE
    inputType: FreeText
    description: ''
    defaultValue: QUIX
    required: false
  - name: DB
    inputType: FreeText
    description: ''
    defaultValue: QUIX
    required: false
  - name: SCHEMA
    inputType: FreeText
    description: ''
    defaultValue: default
    required: false
  - name: TABLE
    inputType: FreeText
    description: ''
    defaultValue: sensordata
    required: false
  - name: CONSUMER_GROUP
    inputType: FreeText
    description: ''
    defaultValue: sink
    required: false
  - name: ROLE
    inputType: FreeText
    description: ''
    defaultValue: SECURITYADMIN
    required: false
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
libraryItemId: starter-destination
