name: snowflake
language: python
variables:
  - name: input
    inputType: InputTopic
    description: Name of the input topic to listen to.
    defaultValue: sensor-data
    required: false
  - name: ACCOUNT
    inputType: FreeText
    description: ''
    defaultValue: XY66326
    required: false
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
libraryItemId: starter-destination
