name: PostgreSQL Sink
language: python
variables:
  - name: input
    inputType: InputTopic
    description: This is the input topic
    defaultValue: sensor-data
    required: true
  - name: PROJECT_ID
    inputType: FreeText
    description: The BigQuery GCP Project ID
    defaultValue: portalanalytics-391408
    required: true
  - name: DATASET_ID
    inputType: FreeText
    description: The target BigQuery dataset ID
    defaultValue: sdfdev
    required: true
  - name: DATASET_LOCATION
    inputType: FreeText
    description: Location of BigQuery dataset
    defaultValue: ' europe-west3'
    required: true
  - name: TABLE_NAME
    inputType: FreeText
    description: Name of the destination table.
    defaultValue: postgres-cdc
    required: true
  - name: CONSUMER_GROUP
    inputType: FreeText
    description: Kafka consumer group.
    defaultValue: postgres-sink-v1
    required: true
  - name: SERVICE_ACCOUNT_JSON
    inputType: Secret
    description: JSON string of the service account file for the BigQuery GCP project
    defaultValue: big_query_secret_json
    required: true
  - name: MAX_QUEUE_SIZE
    inputType: FreeText
    description: Max queue size for the sink ingestion
    defaultValue: 50
    required: true
  - name: POSTGRES_PASSWORD
    inputType: Secret
    defaultValue: POSTGRES_PASSWORD_key
    required: false
  - name: POSTGRES_HOST
    inputType: FreeText
    defaultValue: quixpostgresql.postgres.database.azure.com
    required: false
  - name: POSTGRES_PORT
    inputType: FreeText
    defaultValue: 5432
    required: false
  - name: POSTGRES_DB
    inputType: FreeText
    defaultValue: postgres
    required: false
  - name: POSTGRES_USER
    inputType: FreeText
    defaultValue: postgres
    required: false
  - name: POSTGRES_TABLE_NAME
    inputType: FreeText
    defaultValue: sensor-data
    required: false
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
#libraryItemId: big-query-sink
