name: counter
language: csharp
variables:
  - name: input
    inputType: InputTopic
    description: Name of the input topic to listen to.
    defaultValue: raw
    required: false
  - name: output
    inputType: OutputTopic
    description: Name of the output topic to write to.
    defaultValue: transform
    required: false
dockerfile: dockerfile
runEntryPoint: src/main/java/com/example/MessageCountPerSecond.java
defaultFile: src/main/java/com/example/MessageCountPerSecond.java
libraryItemId: kstreams
