apiVersion: 1

datasources:
  - name: "influxdb"
    type: "influxdb"
    uid: "de3ph94bwuxa8c"
    access: "proxy"
    url: "http://influxdb:80"
    isDefault: true
    basicAuth: false
    basicAuthUser: "admin"
    withCredentials: false
    jsonData:
      dbName: "quix"
      httpMode: "POST"
      organization: "quix"
      version: "Flux"
    secureJsonData:
      token: "${INFLUXDB_TOKEN}"            
    version: 8
    readOnly: false
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:80
    isDefault: false
    editable: true
    jsonData:
      tlsSkipVerify: true