name: Web Gateway
language: python
variables:
  - name: output
    inputType: OutputTopic
    description: This is the output topic for hello world data
    defaultValue: raw
    required: true
dockerfile: build/dockerfile
runEntryPoint: main.py
defaultFile: main.py
