name: http-telegraf-source
language: Python
variables:
  - name: OUTPUT_TOPIC
    inputType: OutputTopic
    description: Name of the output topic to write into
    defaultValue: test
    required: true
dockerfile: dockerfile
runEntryPoint: dockerfile
defaultFile: dockerfile
