name: http-telegraf-source
language: Python
variables:
  - name: INFLUX_TOKEN
    inputType: Secret
    description: ''
    defaultValue: influx_token
    required: true
  - name: PROMETHEUS_URLS
    inputType: FreeText
    description: ''
    defaultValue: ''
    required: true
dockerfile: dockerfile
runEntryPoint: dockerfile
defaultFile: dockerfile
