name: InfluxDb
language: python
variables:
  - name: INIT_ADMIN_TOKEN
    inputType: Secret
    description: ''
    defaultValue: influx_token
    required: true
  - name: ADMIN_PASSWORD
    inputType: Secret
    description: ''
    defaultValue: ADMIN_PASSWORD
    required: false
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
