name: InfluxDb
language: python
variables:
  - name: INIT_ADMIN_TOKEN
    inputType: Secret
    description: ''
    defaultValue: influx_token
    required: true
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
