# Use the official InfluxDB image from the Docker Hub
FROM influxdb:latest

# Set the environment variable for InfluxDB data directory
ENV DOCKER_INFLUXDB_DATA_DIR /app/state/influxdb/data
ENV DOCKER_INFLUXDB_META_DIR /app/state/influxdb/meta
ENV DOCKER_INFLUXDB_WAL_DIR /app/state/influxdb/wal

RUN mkdir -p /app/state/

ENV DOCKER_INFLUXDB_INIT_ADMIN_TOKEN mysecret_token  # Use a strong token here
ENV DOCKER_INFLUXDB_ADMIN_USER myadmin
ENV DOCKER_INFLUXDB_ADMIN_PASSWORD mypassword
ENV DOCKER_INFLUXDB_ORG myorg
ENV DOCKER_INFLUXDB_BUCKET mybucket
ENV DOCKER_INFLUXDB_INIT_MODE setup
ENV DOCKER_INFLUXDB_INIT_USERNAME admin
ENV DOCKER_INFLUXDB_INIT_PASSWORD admin_password
ENV DOCKER_INFLUXDB_INIT_ORG myorg
ENV DOCKER_INFLUXDB_INIT_BUCKET mybucket

# Create the required directories
RUN mkdir -p /app/state/influxdb/data /app/state/influxdb/meta /app/state/influxdb/wal

# Copy the InfluxDB configuration file if needed
# ADD influxdb.conf /etc/influxdb/influxdb.conf

# Expose the necessary ports (8086 is the default port for InfluxDB)
EXPOSE 8086

# Define the default command to run when starting the container
CMD ["influxd", "--reporting-disabled", "--bolt-path", "/app/state/influxdb/influxd.bolt", "--engine-path", "/app/state/influxdb/engine", "--store", "bolt"]